# Generated by Django 4.1.2 on 2022-10-28 20:51

import api.fields.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', api.fields.fields.FirstNameField(max_length=50)),
                ('last_name', api.fields.fields.LastNameField(max_length=50)),
                ('email_address', api.fields.fields.EmailAddressField(max_length=254)),
                ('phone_number', api.fields.fields.PhoneNumberField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('test_field', models.PositiveSmallIntegerField(blank=True, default=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('test_field', models.PositiveSmallIntegerField(blank=True, default=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TutorOrgManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('test_field', models.PositiveSmallIntegerField(blank=True, default=32, null=True)),
            ],
        ),
    ]
