
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/src
      - /src/node_modules
      - /src/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped


  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    volumes:
      - ./backend:/src
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    depends_on:
      - db
    command: ["/bin/bash","./wait-for-it.sh", "db:5432", "--", "./docker-entrypoint.sh"]
    restart: unless-stopped


  db:
    container_name: database
    image: postgres:14
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped