version: "3.9"

services:
  frontend:
    image: frontend
    build: ./frontend
    volumes:
      - ./frontend_volume:/source
    ports:
      - "3000:3000"
    depends_on:
      - backend



  backend:
    image: backend
    build: ./backend
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_volume:/source
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    depends_on:
      - db




  db:
    image: postgres
    volumes:
      - ./db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  